ALTER TABLE room ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE student_section ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE subject ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;
ALTER TABLE student ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;