DROP TABLE IF EXISTS schedules;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS subject_teachers;
DROP TABLE IF EXISTS subject;
DROP TABLE IF EXISTS student_section;
DROP TABLE IF EXISTS teacher;
DROP TABLE IF EXISTS room;
DROP TABLE IF EXISTS "user";